  drop TABLE if exists t_goods;
  -- 建表SQL
  CREATE TABLE t_goods (
  id bigint(20) NOT NULL COMMENT '主键',
          brand_id  bigint(20)  NULL  COMMENT '品牌ID',
          product_category_id  bigint(20)  NULL  COMMENT '类目id',
          feight_template_id  bigint(20)  NULL  COMMENT '运费模板',
          product_attribute_category_id  bigint(20)  NULL  COMMENT '属性分类id',
          name   varchar(255)  NULL  COMMENT '名称',
          pic   varchar(255)  NULL  COMMENT '图片',
          product_sn   varchar(255)  NULL  COMMENT '货号',
          delete_status  int(10)  NULL  COMMENT '删除状态：0->未删除；1->已删除',
          publish_status  int(10)  NULL  COMMENT '上架状态：0->下架；1->上架',
          new_status  int(10)  NULL  COMMENT '新品状态:0->不是新品；1->新品',
          recommand_status  int(10)  NULL  COMMENT '推荐状态；0->不推荐；1->推荐',
          verify_status  int(10)  NULL  COMMENT '审核状态：0->未审核；1->审核通过',
          sort  bigint(20)  NULL  COMMENT '排序',
          sale  int(10)  NULL  COMMENT '销量',
          price  DECIMAL    NULL  COMMENT '价格',
          promotion_price  bigint(20)  NULL  COMMENT '促销价格',
          gift_growth  int(10)  NULL  COMMENT '赠送的成长值',
          gift_point  int(10)  NULL  COMMENT '赠送的积分',
          use_point_limit  int(10)  NULL  COMMENT '限制使用的积分数',
          sub_title   varchar(255)  NULL  COMMENT '副标题',
          description   varchar(255)  NULL  COMMENT '商品描述',
          original_price  bigint(20)  NULL  COMMENT '市场价',
          stock  int(10)  NULL  COMMENT '库存',
          low_stock  int(10)  NULL  COMMENT '库存预警值',
          unit   varchar(255)  NULL  COMMENT '单位',
          weight  bigint(20)  NULL  COMMENT '商品重量，默认为克',
          preview_status  int(10)  NULL  COMMENT '是否为预告商品：0->不是；1->是',
          service_ids   varchar(255)  NULL  COMMENT '以逗号分割的产品服务：1->无忧退货；2->快速退款；3->免费包邮',
          keywords   varchar(255)  NULL  COMMENT '关键词',
          note   varchar(255)  NULL  COMMENT '备注',
          album_pics   varchar(255)  NULL  COMMENT '画册图片，连产品图片限制为5张，以逗号分割',
          detail_title   varchar(255)  NULL  COMMENT '详细标题',
          detail_desc   varchar(255)  NULL  COMMENT '详情描述',
          detail_html   varchar(255)  NULL  COMMENT '产品详情网页内容',
          detail_mobile_html   varchar(255)  NULL  COMMENT '移动端网页详情',
          promotion_start_time  timestamp  NULL  COMMENT '促销开始时间',
          promotion_end_time  timestamp  NULL  COMMENT '促销结束时间',
          promotion_per_limit  int(10)  NULL  COMMENT '活动限购数量',
          promotion_type  int(10)  NULL  COMMENT '促销类型：0->没有促销使用原价;1->使用促销价；2->使用会员价；3->使用阶梯价格；4->使用满减价格；5->限时购',
          brand_name   varchar(255)  NULL  COMMENT '品牌名称',
          product_category_name   varchar(255)  NULL  COMMENT '商品分类名称',
  `db_create_author` varchar(64) DEFAULT NULL COMMENT '操作人',
  `db_create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `db_update_author` varchar(64) DEFAULT NULL COMMENT '编辑人',
  `db_update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品信息';
